version: "3"

services:
  hasura:
    build:
      context: ../docker/hasura
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    volumes:
      - ../hasura:/app
    user: ${APP_UID}
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_ENDPOINT: http://graphql-engine:8080
    tty: true
    restart: unless-stopped
