version: "3"

services:
  graphql-engine:
    image: hasura/graphql-engine:v2.8.4
    expose:
      - 8080
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: guest
    networks:
      - default
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-graphql-engine.rule=Host(`${APP_HOST}`) && PathPrefix(`/console`, `/v1`, `/v2`, `/api`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-graphql-engine.priority=1000
    restart: unless-stopped

networks:
  web:
    external: true
