version: "3"

services:
  traefik:
    image: traefik:2.5
    command:
      - --accesslog=false
      - --api.insecure=true
      - --entryPoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=web
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  web:
    external: true
