version: "3"

services:
  admin:
    build: ../docker/node-alpine
    working_dir: /app
    user: ${APP_UID}
    volumes:
      - ../admin:/app
    expose:
      - 3000
    command: sh -c 'yarn && yarn dev'
    networks:
      - default
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-admin.rule=Host(`${APP_HOST}`)
    restart: unless-stopped

networks:
  web:
    external: true
